plugins {
    id 'com.android.application'
}

android {
    namespace 'jp.local.fax2840usb'
    compileSdk 35

    defaultConfig {
        applicationId 'jp.local.fax2840usb'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '0.4.0-diagnostic'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
